version: '3.8'

services:
  bbp_postgres:
    image: postgres:15-alpine
    container_name: bbp_postgres
    restart: always
    shm_size: 1gb
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: >
      postgres 
      -c shared_buffers=512MB 
      -c work_mem=64MB 
      -c maintenance_work_mem=128MB 
      -c effective_cache_size=1GB
      -c max_wal_size=1GB
    volumes:
      - bbp-db-data:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bbp-network

  bbp_redis:
    image: redis:7-alpine
    container_name: bbp_redis

    restart: always
    networks:
      - bbp-network

  bbp_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bbp_api
    # Теперь команда чистая, без npm install
    command: npm run api:dev
    volumes:
      - .:/app
      - /app/node_modules

    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    ports:
      - "${APP_PORT:-8001}:3000"
    networks:
      - bbp-network
    depends_on:
      bbp_postgres:
        condition: service_healthy
      bbp_redis:
        condition: service_started

  bbp_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bbp_worker
    restart: always
    command: sh -c "xvfb-run -a --server-args='-screen 0 1280x1024x24' node src/worker/main.js"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      USE_PROXY: ${USE_PROXY}
      PROXY_SERVER: ${PROXY_SERVER}
      PROXY_USERNAME: ${PROXY_USERNAME}
      PROXY_PASSWORD: ${PROXY_PASSWORD}
    networks:
      - bbp-network
    depends_on:
      bbp_postgres:
        condition: service_healthy
      bbp_redis:
        condition: service_started

  bbp_ui:
    build:
      context: ./UI
      dockerfile: Dockerfile
    container_name: bbp_ui
    ports:
      - "5174:5174" 
    volumes:
      - ./UI:/app
      - /app/node_modules
    networks:
      - bbp-network  
    environment:
      - NODE_ENV=development
    depends_on:
      - bbp_api      

volumes:
  bbp-db-data:

networks:
  bbp-network:
    driver: bridge